# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Tracker_for_tracking_habits' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Tracker_for_tracking_habits
  pod 'YandexMobileMetrica/Dynamic', '4.5.0'

  target 'Tracker_for_tracking_habitsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
